---
# Setup LAMP Stack
- hosts: all
  tasks:
    - name: install lamp packages
      become: yes
      become_method: sudo
      apt: name= ['apache2', 'mysql-server', 'php5-mysql', 'php5'] update_cache=yes state=latest
      with_items:
        - apache2
        - mysql-server
        - php5-mysql
        - php5
      
    - name: start services
      service: name= {{ item }} state=started enabled=yes
      become: yes
      become_method: sudo
      with_items:
        - apache2
        - mysql

    - name: deploy index.html
      become: yes
      become_method: sudo
      copy:
        src: index.html
        dest: /var/www/html/index.html
       
