---
# Setup LAMP Stack
- hosts: all
  tasks:
    - name: install lamp stack
      become: yes
      become_user: root
      apt: name={{ item }} state=present update_cache=yes
      with_items:
        - apache2
        - mysql-server
        - php7.0
        - php7.0-mysql

    - name: start services
      service: name={{ item }} state=started enabled=yes
      become: yes
      become_user: root
      with_items:
        - apache2
        - mysql

    - name: deploy index.html
      become: yes
      become_user: root
      copy:
        src: /home/MIQDIGITAL/nandeesh/lamp/awxansible/index.html
        dest: /var/www/html/index.html
       
