---
# Setup LAMP Stack
- hosts: all
  tasks:
    - name: install lamp stack
      become: yes
      become_method: sudo
      apt: name= "{{ item }}" state=present
      with_items:
        - apache2
        - mysql-server
        - php7.0
        - php7.0-mysql

    - name: start services
      service: name= "{{ item }}" state=started enabled=yes
      become: yes
      become_method: sudo
      with_items:
        - apache2
        - mysql

    - name: deploy index.html
      become: yes
      become_method: sudo
      copy:
        src: index.html
        dest: /var/www/html/index.html
       
