- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest update_cache=yes cache_valid_time=3600
      register: apt_result
      until: apt_result|success
      retries: 3
      delay: 1
      ignore_errors: yes

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port 8081
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8081" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 8081
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8081>" state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
